org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.20.2)
forge_version=47.2.20
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

mod_id=lootoverflow
mod_name=LootOverflow
mod_license=MIT
mod_version=1.0.0
mod_group_id=com.lootoverflow
mod_authors=satan007
mod_description=Prevents dungeon chest loot from multiple mods being lost when it overflows the chest's slots.
